sudo: required
dist: bionic
language: c

install:
  - sudo apt-get install gcc-avr binutils-avr avr-libc jq

before_script:
  - avr-gcc --version

script:
  - make clean
  - make

after_success:
  - export PRETTYNAME=jan
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
  - curl -s https://www.adafruit.com/api/quotes.php?random=1 | jq -r '.[0] | .text, .author'