sudo: required
dist: bionic
language: c

install:
  - sudo apt-get install gcc-avr binutils-avr avr-libc doxygen

before_script:
  - avr-gcc --version

script:
  - make clean
  - make

after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/caternuson/travis-ci/master/doxygen_generate.sh)
